import { ROLES_ENUM } from "src/app/constants/roles.enum";

export const RESOURCE_BY_ROLES = {
    PANEL_INVITADO: [ROLES_ENUM.INVITADO, ROLES_ENUM.ADMIN],
    PANEL_ADMIN: [ROLES_ENUM.ADMIN],
    PANEL_PROVEEDOR: [ROLES_ENUM.PROVEEDOR]
}